export const dictionary={reviewing:'xem xét',documents:'tài liệu',loading:'chất hàng',passengers:'hành khách',departure:'khởi hành',postponed:'bị hoãn',available:'có sẵn/rảnh',warehouse:'nhà kho',conference:'hội nghị',registration:'đăng ký',participants:'người tham gia',qualified:'đủ năng lực',efficiently:'hiệu quả',shipment:'lô hàng',deadline:'hạn chót',regarding:'về việc',despite:'mặc dù',equipment:'thiết bị',maintenance:'bảo trì',complimentary:'miễn phí',reservation:'đặt chỗ',attached:'đính kèm',approximately:'xấp xỉ',annual:'hằng năm',requirement:'yêu cầu',response:'phản hồi',purchase:'mua hàng',policy:'chính sách',receipt:'biên lai',shelves:'kệ hàng',foreground:'tiền cảnh',background:'hậu cảnh',arranging:'sắp xếp',technician:'kỹ thuật viên',repairing:'sửa chữa',counter:'quầy',announcement:'thông báo',platform:'sân ga',delay:'trì hoãn',issue:'vấn đề',venue:'địa điểm',inquiry:'yêu cầu thông tin',appreciate:'cảm kích',confirm:'xác nhận',schedule:'lịch trình',invoice:'hóa đơn',replacement:'sản phẩm thay thế'}

const scenes=[
 ['A woman is reviewing some documents at a desk.','Người phụ nữ đang xem tài liệu tại bàn.','reviewing/removing là bẫy gần âm; hành động đang diễn ra nên dùng is reviewing.'],
 ['Some workers are loading boxes onto a truck.','Một số công nhân đang chất thùng lên xe tải.','Are loading diễn tả đúng hành động; onto chỉ hướng lên xe.'],
 ['Guests are standing at a reception counter.','Các vị khách đang đứng tại quầy lễ tân.','Chỉ mô tả điều nhìn thấy, không suy đoán họ đang nhận phòng.'],
 ['A technician is repairing a printer.','Một kỹ thuật viên đang sửa máy in.','Máy chưa sửa xong nên không dùng has been repaired.'],
 ['Several people are seated around a conference table.','Một số người đang ngồi quanh bàn hội nghị.','Be seated mô tả trạng thái ngồi; không dùng are seating.'],
 ['A server is carrying plates through a restaurant.','Một nhân viên phục vụ đang mang các đĩa thức ăn.','Carrying là hành động nhìn thấy rõ, các ý gọi món là suy diễn.'],
 ['Passengers are waiting near an airport gate.','Hành khách đang chờ gần cửa ra máy bay.','Không suy đoán máy bay đang cất cánh chỉ vì thấy nó ngoài cửa sổ.'],
 ['An employee is arranging products on shelves.','Một nhân viên đang sắp xếp hàng trên kệ.','Bẫy reaching/arranging; nhiều sản phẩm cho thấy hành động sắp xếp.'],
 ['Two colleagues are looking at a laptop.','Hai đồng nghiệp đang nhìn vào máy tính.','Look at là cụm đúng; laptop vẫn đang được sử dụng.'],
 ['Construction workers are examining a document.','Các công nhân xây dựng đang xem tài liệu.','Công trình chưa hoàn thành; examining là điều quan sát được.']
]
const distractors=[['She is removing a desk.','The documents are being delivered.','She has closed her laptop.'],['The truck is being repaired.','The boxes have been opened.','A worker is driving away.'],['The counter is being painted.','The guests are carrying desks.','A room has been cleaned.'],['Some papers are being copied.','The printer has been removed.','A man is purchasing equipment.'],['A conference room is being constructed.','Everyone is leaving the building.','Some chairs are being stacked.'],['A server is clearing every table.','Some meals are being ordered.','The restaurant has closed.'],['Some luggage is being weighed.','A plane is taking off.','Tickets have been sold.'],['A customer is paying at the counter.','The shelves are completely empty.','A woman is reaching for a receipt.'],['They are putting the computer away.','A presentation has ended.','They are writing on a wall.'],['The workers are removing their helmets.','A building has been completed.','The men are operating a vehicle.']]
const slots=[1,2,0,1,1,2,0,2,0,2]
const p1=scenes.map((s,i)=>{let options=[...distractors[i]];options.splice(slots[i],0,s[0]);return{id:`p1-${i+1}`,image:i,prompt:'Choose the statement that best describes the picture.',speech:options,options,answer:slots[i],translation:s[1],explanation:s[2],tip:'Gọi tên chủ thể + hành động nhìn thấy; không suy diễn.'}})

const p2data=[
 ['When will the new schedule be announced?','Khi nào lịch mới sẽ được thông báo?',['At the front desk.','Probably this afternoon.','The announcement was clear.'],1,'When cần thời gian; C chỉ lặp âm announce/announcement nhưng sai ý.'],
 ['Who is responsible for ordering supplies?','Ai chịu trách nhiệm đặt vật tư?',['Ms. Chen handles that.','They arrived yesterday.','In the supply room.'],0,'Who hỏi người; tên hoặc chức vụ là đáp án hợp lệ.'],
 ['Where should I leave these invoices?','Tôi nên để hóa đơn ở đâu?',['About fifty dollars.','I already paid it.','On my desk, please.'],2,'Where hỏi nơi chốn; on my desk chỉ đúng vị trí.'],
 ['Why was the meeting postponed?','Tại sao cuộc họp bị hoãn?',['The manager was out of town.','Until next Tuesday.','In the main conference room.'],0,'Why cần lý do; người quản lý đi vắng là nguyên nhân hợp lý.'],
 ['Could you help me move this cabinet?','Bạn giúp tôi di chuyển tủ này được không?',['It is a new cabinet.','Sure, after I finish this call.','Near the window.'],1,'Could you là lời nhờ; Sure là phản hồi tự nhiên.'],
 ["Haven’t you submitted the expense report yet?",'Bạn vẫn chưa nộp báo cáo chi phí à?',["No, I’m still working on it.",'The expenses were high.','To the accounting department.'],0,'No xác nhận là chưa nộp; vế sau giải thích rõ.'],
 ['How often is the equipment inspected?','Thiết bị được kiểm tra thường xuyên thế nào?',['For about an hour.','Every three months.','By a technician.'],1,'How often hỏi tần suất; every three months.'],
 ["Why don’t we take an earlier train?",'Chúng ta đi chuyến tàu sớm hơn nhé?',['Platform number four.',"That’s a good idea.",'It arrived on time.'],1,"Why don’t we là đề nghị chứ không hỏi nguyên nhân."],
 ['Did Maria reserve the conference room?','Maria đã đặt phòng hội nghị chưa?',['It seats twenty people.','I thought you were going to do it.','The conference was useful.'],1,'Câu trả lời gián tiếp ngụ ý Maria chưa làm.'],
 ['Which printer should I use?','Tôi nên dùng máy in nào?',['The one next to the window.','Some paper and ink.','Yes, it prints quickly.'],0,'Which hỏi lựa chọn; the one xác định đúng chiếc máy.']]
const p2=p2data.map((x,i)=>({id:`p2-${i+1}`,prompt:x[0],speech:x[0],translation:x[1],options:x[2],answer:x[3],explanation:x[4],tip:'Nghe từ hỏi đầu tiên rồi loại đáp án sai loại thông tin.'}))

const r5data=[
 ['All conference _____ must register before Friday.',['participate','participants','participation','participatory'],1,'Tất cả người tham dự hội nghị phải đăng ký trước thứ Sáu.','Cần danh từ số nhiều chỉ người làm chủ ngữ; participants là người tham gia.','All + danh từ đếm được số nhiều.'],
 ['The new system allows employees to work more _____.',['efficient','efficiency','efficiently','efficiencies'],2,'Hệ thống mới cho phép nhân viên làm việc hiệu quả hơn.','Chỗ trống bổ nghĩa cho động từ work nên cần trạng từ efficiently.','Động từ thường + trạng từ.'],
 ['Ms. Park is responsible _____ preparing the report.',['at','for','with','by'],1,'Cô Park chịu trách nhiệm chuẩn bị báo cáo.','Cụm cố định be responsible for; sau for dùng V-ing.','Học nguyên cụm responsible for.'],
 ['_____ the heavy rain, the event continued as planned.',['Although','Despite','Because','Therefore'],1,'Mặc dù mưa lớn, sự kiện vẫn tiếp tục như kế hoạch.','Sau chỗ trống là cụm danh từ nên dùng Despite; Although cần S + V.','Despite + N; Although + S + V.'],
 ['Employees should submit _____ travel receipts.',['they','them','their','theirs'],2,'Nhân viên nên nộp biên lai đi lại của họ.','Trước danh từ travel receipts cần tính từ sở hữu their.','Trước danh từ → my/your/their.'],
 ['The team _____ the system last Tuesday.',['inspects','has inspected','inspected','will inspect'],2,'Đội đã kiểm tra hệ thống vào thứ Ba tuần trước.','Last Tuesday là thời điểm quá khứ đã kết thúc nên dùng inspected.','Last/yesterday/ago → quá khứ đơn.'],
 ['Please contact the supplier _____ the damaged shipment.',['regarding','between','during','beside'],0,'Vui lòng liên hệ nhà cung cấp về lô hàng bị hỏng.','Regarding nghĩa là về/về vấn đề, đúng ngữ cảnh công sở.','Regarding = about trong email.'],
 ['The hotel offers _____ breakfast to all guests.',['compliment','compliments','complimentary','complimentarily'],2,'Khách sạn cung cấp bữa sáng miễn phí cho mọi khách.','Trước breakfast cần tính từ; complimentary nghĩa là miễn phí.','Trước danh từ → ưu tiên tính từ.'],
 ['Neither the manager nor her assistants _____ available.',['is','are','was','has'],1,'Cả quản lý lẫn trợ lý đều không rảnh.','Neither...nor hòa hợp với chủ ngữ gần nhất; assistants số nhiều nên dùng are.','Nhìn danh từ ngay trước động từ.'],
 ['Customers may request a full _____ within 30 days.',['refund','refunds','refunded','refundable'],0,'Khách có thể yêu cầu hoàn tiền đầy đủ trong 30 ngày.','Sau a full cần danh từ số ít; refund là khoản hoàn tiền.','a/an + tính từ + danh từ số ít.']]
const r5=r5data.map((x,i)=>({id:`r5-${i+1}`,prompt:x[0],options:x[1],answer:x[2],translation:x[3],explanation:x[4],tip:x[5]}))

const readTexts=['Attention, passengers. Flight 286 to Singapore will depart from Gate 14 instead of Gate 9. Please proceed to the new gate immediately. Boarding will begin at six forty-five. We apologize for any inconvenience caused by this last-minute change.','Welcome to the Lakeside Business Conference. Registration opens at eight thirty in the main lobby. The opening presentation will begin promptly at nine. Participants are reminded to wear their name badges throughout the event and silence mobile phones during all sessions.','This weekend only, Carson Office Supply is offering twenty percent off all desk chairs and lighting products. Visit our downtown showroom between nine and six, or place your order online. Free delivery is available for purchases over one hundred dollars.','May I have your attention, please? The north parking area will be closed for maintenance beginning Monday morning. Employees should use the visitor lot beside Building C. Additional shuttle service will be provided every fifteen minutes throughout the week.','Thank you for calling Greenway Medical Center. Our office is open Monday through Friday from eight a.m. to five p.m. To schedule an appointment, press one. For billing questions, press two. For all other inquiries, please remain on the line.','The museum café will close at four thirty today for a private event. Visitors may purchase refreshments from the kiosk near the main entrance. The café will reopen tomorrow at its regular time of nine o’clock. Thank you for your understanding.','Good morning, everyone. Before today’s factory tour begins, please put on the safety glasses provided at the entrance. Stay with your assigned group at all times, and do not touch any machinery unless your guide gives you permission.','Our spring gardening workshops begin next Saturday. Experienced instructors will demonstrate how to select plants, prepare soil, and maintain a healthy garden. Space is limited, so register online by Wednesday to reserve your place in the program.','Passengers traveling on the seven-fifteen train to Brighton should be advised that service has been delayed approximately twenty minutes. We expect the train to arrive at Platform 3 shortly. Updated information will appear on the station monitors.','Thank you for visiting the Harbor Hotel. Breakfast is served in the second-floor restaurant from six thirty until ten. The fitness center is open twenty-four hours a day. Please contact reception if you need towels, transportation, or local recommendations.']
const titles=['Airport announcement','Conference welcome','Store advertisement','Parking notice','Telephone message','Museum notice','Factory tour','Workshop advertisement','Train delay','Hotel information']
const s1=readTexts.map((text,i)=>({id:`s1-${i+1}`,prompt:text,title:titles[i],tip:'Ngắt hơi ở dấu câu; nhấn từ chỉ giờ, địa điểm và hành động.'}))
const actions=['reviewing documents at her desk','loading boxes onto a truck','speaking with guests at reception','repairing an office printer','having a meeting around a table','carrying plates in a restaurant','waiting near an airport gate','arranging products on shelves','looking at a laptop together','examining plans at a construction site']
const s2=actions.map((action,i)=>({id:`s2-${i+1}`,image:i,prompt:'Describe the picture in as much detail as you can.',outline:['Mở cảnh: This picture was taken at...','Nói hành động chính: I can see...','Thêm foreground/background và nhận xét chung.'],sample:`This picture was taken at a workplace. The main subject is ${action}. In the background, I can see details related to the work environment. Overall, everyone seems focused.`}))
const keys=[['woman','documents'],['workers','truck'],['guests','counter'],['technician','printer'],['people','meeting'],['server','plates'],['passengers','gate'],['employee','shelves'],['colleagues','laptop'],['workers','plans']]
const w1=keys.map((keywords,i)=>({id:`w1-${i+1}`,image:i,keywords,prompt:`Write ONE sentence using both words: ${keywords.join(' / ')}.`,sample:['The woman is reviewing documents at her desk.','The workers are loading boxes onto a truck.','The guests are standing at the reception counter.','A technician is repairing the printer.','Several people are having a meeting.','The server is carrying plates through the restaurant.','Passengers are waiting near the airport gate.','An employee is arranging products on the shelves.','Two colleagues are looking at a laptop.','The workers are examining the plans.'][i],tip:'Dùng đủ hai từ, chia động từ đúng và kết thúc bằng dấu chấm.'}))
const emails=[['Meeting reschedule','A client wants to move Friday’s meeting and asks for two available times.','I am available next Monday at 10 a.m. or Tuesday at 2 p.m.'],['Damaged order','A customer received a damaged item and requests a solution.','We can send a free replacement or provide a full refund.'],['Conference information','An attendee asks about registration time and parking.','Registration starts at 8:30 a.m. Free parking is behind the center.'],['Hotel reservation','A guest asks about early check-in and airport transport.','Early check-in starts at noon. Our airport shuttle runs hourly.'],['Training course','An employee asks about the schedule and materials.','The course is Wednesday from 9 to 4. Please bring a laptop.'],['Invoice correction','A supplier reports an incorrect quantity on an invoice.','We will review the order and send a corrected invoice tomorrow.'],['Office maintenance','A tenant reports that the air conditioner is broken.','A technician will visit tomorrow between 9 and 11 a.m.'],['Job interview','An applicant asks what to bring and how long it takes.','Please bring an ID and résumé. The interview lasts about 45 minutes.'],['Event cancellation','A guest asks why an event was canceled and about refunds.','The event was canceled due to weather. Refunds take five business days.'],['Product inquiry','A customer asks if a chair is available and delivery is free.','The chair is in stock. Delivery is free for orders over $100.']]
const w2=emails.map((x,i)=>({id:`w2-${i+1}`,title:x[0],prompt:x[1],framework:['Cảm ơn/xác nhận email','Trả lời đủ yêu cầu bằng thông tin cụ thể','Kết thư và mời liên hệ lại'],sample:`Dear Customer,\n\nThank you for your email. ${x[2]} Please let me know if you need any further information.\n\nBest regards,\nAlex`}))

export const parts=[{id:'listening-1',skill:'Listening',part:'Part 1',title:'Mô tả tranh',description:'Photographs · Bẫy hành động & trạng thái',questions:p1,time:15,type:'quiz',accent:'orange'},{id:'listening-2',skill:'Listening',part:'Part 2',title:'Hỏi – đáp',description:'Question–Response · Trả lời gián tiếp',questions:p2,time:12,type:'quiz',accent:'orange'},{id:'reading-5',skill:'Reading',part:'Part 5',title:'Hoàn thành câu',description:'Incomplete Sentences · Ngữ pháp & từ vựng',questions:r5,time:20,type:'quiz',accent:'green'},{id:'speaking-1',skill:'Speaking',part:'Part 1',title:'Đọc thành tiếng',description:'Read a Text Aloud · 45 giây',questions:s1,time:45,type:'speaking',accent:'blue'},{id:'speaking-2',skill:'Speaking',part:'Part 2',title:'Miêu tả tranh',description:'Describe a Picture · Dàn ý 3 bước',questions:s2,time:45,type:'speaking',accent:'blue'},{id:'writing-1',skill:'Writing',part:'Part 1',title:'Viết câu theo tranh',description:'Picture Sentence · 2 từ bắt buộc',questions:w1,time:60,type:'writing',accent:'purple'},{id:'writing-2',skill:'Writing',part:'Part 2',title:'Phản hồi email',description:'Email Response · Khung mục tiêu 150+',questions:w2,time:420,type:'writing',accent:'purple'}]

export const tipGroups=[
 {id:'word-form',category:'Reading Part 5',title:'Mẹo đuôi từ loại',summary:'Nhận diện loại từ trong 3 giây mà chưa cần dịch cả câu.',tags:['Part5_TuLoai','DuoiTu'],color:'green',sections:[
  {title:'Danh từ chỉ vật/khái niệm',items:['-tion, -sion, -ment, -ance, -ence, -ity, -ship, -ness, -ism','Ví dụ: information, decision, payment, performance, responsibility.']},
  {title:'Danh từ chỉ người',items:['-er, -or, -ant, -ee, -ist','Danh từ chỉ người số ít đếm được thường cần a/an; số nhiều thường có -s. Ví dụ: an applicant, two employees.']},
  {title:'Tính từ và trạng từ',items:['Tính từ: -ful, -less, -ive, -able, -ible, -ous, -ic, -al, -ent, -ant.','Trạng từ thường có dạng tính từ + -ly. Bỏ -ly thường tìm được tính từ gốc.','Ngoại lệ cần nhớ: friendly, costly, likely là tính từ; fast, hard, late có thể là trạng từ không có -ly.']}]},
 {id:'golden-position',category:'Reading Part 5',title:'Mẹo vị trí vàng',summary:'Nhìn hai bên chỗ trống để xác định loại từ trước khi dịch.',tags:['Part5_TuLoai','ViTriVang'],color:'green',sections:[
  {title:'Vị trí thường cần trạng từ',items:['Giữa trợ động từ và động từ chính: have ___ V3, be ___ V-ing, will ___ V-bare.','Giữa động từ và tân ngữ: V + ___ + Object, khi chỗ trống mô tả cách thực hiện hành động.','Trước tính từ: ___ + Adj, ví dụ highly successful. Trạng từ cũng có thể đứng sau tính từ trong một số cấu trúc.']},
  {title:'Đầu câu trước dấu phẩy',items:['___, S + V + O có thể là trạng từ nối như However, Therefore, Fortunately.','Cũng có thể là V-ing/V3 rút gọn hoặc liên từ kèm mệnh đề; phải nhìn cấu trúc phía sau, không chỉ nhìn dấu phẩy.']}]},
 {id:'subject-verb',category:'Reading Part 5',title:'Bẫy chủ ngữ – động từ',summary:'Tìm đúng “chủ ngữ thật”, bỏ qua phần chen giữa.',tags:['Part5_HoaHop','SubjectVerb'],color:'green',sections:[
  {title:'Ba quy tắc lấy điểm',items:['Noun 1 + of/in/with/for + Noun 2: động từ thường chia theo Noun 1. Ví dụ: The list of items is...','V-ing hoặc To-V làm chủ ngữ: thường dùng động từ số ít. Ví dụ: Reading reports takes time.','Someone, everyone, anyone, no one, everything, anything: dùng động từ số ít.']}]},
 {id:'participle-clause',category:'Reading Part 5',title:'Rút gọn mệnh đề quan hệ',summary:'Phân biệt V-ing chủ động và V3/ed bị động.',tags:['Part5_RutGon','Ving_V3'],color:'green',sections:[
  {title:'Cách loại nhanh',items:['Sau chỗ trống có tân ngữ/danh từ mà động từ tác động lên → thường chọn V-ing chủ động.','Sau chỗ trống là by/in/at/with hoặc không có tân ngữ → thường cân nhắc V3/ed bị động.','Luôn hỏi: danh từ phía trước “tự làm” hay “được làm”? Đây là kiểm tra đáng tin cậy hơn vị trí đơn thuần.']}]},
 {id:'subjunctive',category:'Reading Part 5',title:'Câu giả định',summary:'Nhận diện that + S + V nguyên mẫu.',tags:['Part5_GiaDinh','Vbare'],color:'green',sections:[
  {title:'Từ báo hiệu',items:['suggest, recommend, require, request, insist','essential, important, imperative','Cấu trúc: từ yêu cầu + that + S + (should) + V-bare. Ví dụ: We recommend that he arrive early.']}]},
 {id:'although-despite',category:'Liên từ & Giới từ',title:'Mặc dù: Although hay Despite?',summary:'Nhìn ngay sau đáp án là mệnh đề hay cụm danh từ.',tags:['LienTu_GioiTu','Part5_LienTu'],color:'purple',sections:[
  {title:'Bảng phân biệt',items:['Sau S + V → Although, Even though, Though, While.','Sau cụm danh từ/V-ing → Despite, In spite of.','Ví dụ: Although it rained... / Despite the rain...']}]},
 {id:'because-due-to',category:'Liên từ & Giới từ',title:'Bởi vì: Because hay Due to?',summary:'Mệnh đề đi với liên từ; cụm danh từ đi với giới từ.',tags:['LienTu_GioiTu','Part5_LienTu'],color:'purple',sections:[
  {title:'Bảng phân biệt',items:['Sau S + V → Because, Since, As, Now that.','Sau cụm danh từ/V-ing → Because of, Due to, Owing to, On account of, As a result of.','Ví dụ: because the road was closed / due to the road closure.']}]},
 {id:'while-for-during',category:'Liên từ & Giới từ',title:'While, For hay During?',summary:'Ba từ tiếng Việt dễ dịch chung nhưng cấu trúc khác nhau.',tags:['LienTu_GioiTu','Part5_GioiTu'],color:'purple',sections:[
  {title:'Cách chọn',items:['While + S + V: trong khi một mệnh đề xảy ra.','For + khoảng thời gian: for three days, for two hours.','During + danh từ sự kiện/kỳ nghỉ: during the meeting, during the vacation.']}]},
 {id:'listening-part1',category:'Listening',title:'Part 1: Nhìn tay, mắt và trạng thái',summary:'Loại bẫy hành động, trang phục và suy diễn trong tranh.',tags:['Part1_HanhDong','Listening'],color:'orange',sections:[
  {title:'Tranh một người',items:['Tập trung tay/mắt: holding, looking at, reaching for, examining, typing.','Wearing = đã mặc sẵn, mô tả trạng thái. Putting on = đang xỏ/mặc/đội, mô tả hành động. Tranh tĩnh thường chọn wearing nếu không thấy động tác mặc.','Chỉ chọn điều nhìn thấy; không suy đoán nghề nghiệp, cảm xúc hoặc mục đích.']}]},
 {id:'listening-part2-traps',category:'Listening',title:'Part 2: Bẫy đại từ và thời gian',summary:'Loại đáp án sai người, sai thì trước khi xét nghĩa.',tags:['Part2_BayYesNo','Part2_DaiTu','Listening'],color:'orange',sections:[
  {title:'Hai bẫy loại ngay',items:['Câu hỏi nói Mr. David nhưng đáp án dùng She... → loại nếu She không chỉ một người khác hợp lý trong ngữ cảnh.','Câu hỏi did/yesterday nhưng đáp án nói tomorrow/will → thường lệch thời gian, loại nếu không phải câu trả lời gián tiếp hợp lý.']},
  {title:'Đề nghị và mời mọc',items:["Why don’t we...? / Would you like...? thường nhận: Sounds good, I’d love to, Sure, thanks.",'Không đợi Yes/No; ETS thường dùng câu phản hồi tự nhiên hoặc gián tiếp.']}]},
 {id:'listening-part34',category:'Listening',title:'Part 3 & 4: Graphic và câu hàm ý',summary:'Kết hợp audio với bảng biểu, đọc ngữ cảnh quanh câu trích dẫn.',tags:['Part3_Graphic','Part4_HamY','Listening'],color:'orange',sections:[
  {title:'Graphic Questions',items:['Băng đọc thông tin ở một dòng/mục; dò sang ô cùng hàng hoặc cột tương ứng để lấy đáp án.','Đọc trước tiêu đề, nhãn cột và đơn vị; không cố đọc toàn bộ bảng.']},
  {title:'Câu trích dẫn hàm ý',items:['Nghe một câu trước và một câu sau câu trích dẫn.','Xác định mục đích/cảm xúc: từ chối khéo, phàn nàn, sửa kế hoạch hay nhấn mạnh.','Không dịch từng chữ; hỏi câu nói đó khiến người nghe phải làm gì tiếp theo.']}]},
 {id:'guess-listening',category:'Khoanh lụi',title:'Hết giờ: ưu tiên Listening',summary:'Chiến lược giảm rủi ro, không phải công thức bảo đảm đúng.',tags:['Guessing','Part2_BayYesNo'],color:'red',sections:[
  {title:'Khi không nghe kịp Part 2',items:['Ưu tiên cân nhắc câu trả lời ngắn, tự nhiên hoặc một câu hỏi ngược lại.','Các cụm check, depend, haven’t decided thường xuất hiện trong câu trả lời gián tiếp, nhưng chỉ chọn khi hợp ngữ cảnh.','Loại đáp án lặp nguyên từ khóa nhưng không trả lời đúng loại câu hỏi.']}]},
 {id:'guess-reading',category:'Khoanh lụi',title:'Hết giờ: ưu tiên Reading',summary:'Dùng cấu trúc trước, sắc thái từ vựng sau.',tags:['Guessing','Part5_TuVung'],color:'red',sections:[
  {title:'Khi không biết nghĩa',items:['Trước hết loại theo loại từ, số ít/số nhiều và cấu trúc câu.','Nếu vẫn phải đoán câu từ vựng công sở, cân nhắc từ quen và hợp sắc thái như productive, efficient, reliable, convenient.','Không mặc định từ mang nghĩa tích cực luôn đúng; ngữ pháp và cụm từ đi kèm vẫn quyết định đáp án.']}]}
]
