import {legacyQuestionBank as fullQuestionBank} from './data/toeicData'

const sw=(id,question,options,correctAnswer,translation,explanation,fastTip)=>({id:`sw-${id}`,part:'speaking-writing',question,passage:'',options,correctAnswer,vietnameseTranslation:translation,explanation,fastTip})

export const synonymPairs=[
 ['buy','purchase'],['fix','repair'],['delay','postpone'],['help','assist'],['start','begin'],['end','finish'],['choose','select'],['job','position'],['employee','staff'],['customer','client'],['nearby','close to'],['free','at no charge'],['required','necessary'],['approximately','about'],['currently','now'],['increase','rise'],['decrease','decline'],['cancel','call off'],['available','open'],['submit','turn in'],
]

export const speakingWritingQuestions=[
 sw(1,'Choose the best opening sentence to describe an office picture.',['This picture was taken in an office.','I think offices are useful.','Yesterday was a busy day.','There are because many people.'],0,'Bức ảnh này được chụp trong một văn phòng.','Câu A xác định bối cảnh trực tiếp, có chủ ngữ và động từ hoàn chỉnh. B nói quan điểm lệch nhiệm vụ; C không dựa vào tranh; D sai ngữ pháp.','Mở tranh bằng: This picture was taken in + place.'),
 sw(2,'Choose the best sentence for the main person in a picture.',['In the center, a woman is typing on a laptop.','A woman typing laptop center.','The woman was type a laptop.','In center have a woman.'],0,'Ở giữa ảnh, một phụ nữ đang gõ máy tính xách tay.','A có vị trí + chủ thể + is V-ing + vật. B/D thiếu cấu trúc câu; C chia động từ sai.','Tả hành động: vị trí + S + is/are + V-ing.'),
 sw(3,'Choose the best background sentence.',['In the background, some shelves are filled with books.','Background shelf book many.','Some shelves filling books yesterday.','There is shelves in background.'],0,'Ở phía sau, một số kệ chứa đầy sách.','A dùng đúng cụm vị trí và bị động trạng thái. B/C là mảnh câu; D sai hòa hợp there are.','Hậu cảnh: In the background, there is/are...'),
 sw(4,'Choose the clearest personal-question response.',['Twice a week.','I go shopping twice a week, usually on weekends because I have more free time.','Shopping is shop and week.','Yes, shopping.'],1,'Tôi đi mua sắm hai lần một tuần, thường vào cuối tuần vì tôi rảnh hơn.','B đủ ba tầng: trả lời trực tiếp + chi tiết + lý do. A đúng nhưng quá ngắn; C/D không truyền đạt đủ ý.','Speaking: trả lời trực tiếp + chi tiết + because + lý do.'),
 sw(5,'Choose the best opinion opening.',['I prefer working at home for two reasons.','Working home because good.','Maybe office yesterday.','I am prefer work home.'],0,'Tôi thích làm việc tại nhà vì hai lý do.','A nêu quan điểm rõ và báo trước bố cục. B/C thiếu câu hoàn chỉnh; D dùng sai am prefer.','Opinion: I prefer... for two reasons.'),
 sw(6,'Choose the best email opening.',['Thank you for contacting us regarding your order.','Hey, what do you want?','Order contact thanks.','I contacting your order yesterday.'],0,'Cảm ơn bạn đã liên hệ với chúng tôi về đơn hàng.','A lịch sự, đúng ngữ cảnh công sở và đúng cấu trúc regarding + noun. Các câu khác thô hoặc sai ngữ pháp.','Email: Thank you for contacting us regarding...'),
 sw(7,'Choose the best sentence that solves an email request.',['I am pleased to inform you that a replacement will be shipped today.','Replacement maybe good.','You broke it, so wait.','It shipment today pleased.'],0,'Tôi vui mừng thông báo rằng hàng thay thế sẽ được gửi hôm nay.','A trả lời thẳng yêu cầu và cho hành động cụ thể. B mơ hồ; C thiếu lịch sự; D sai cấu trúc.','Thân email: nêu giải pháp + thời điểm cụ thể.'),
 sw(8,'Choose the best professional closing.',['Please feel free to contact me if you need further assistance.','Do not email again.','Contact maybe later.','I finish this email now.'],0,'Xin cứ liên hệ với tôi nếu bạn cần hỗ trợ thêm.','A là câu kết lịch sự và mở kênh hỗ trợ. Các lựa chọn khác thiếu chuyên nghiệp.','Kết email: Please feel free to contact me if...'),
 sw(9,'Which is the strongest four-paragraph essay plan?',['Opinion → two unrelated stories → goodbye','Introduction → Reason 1 with example → Reason 2 with example → Conclusion','Vocabulary list → title → one sentence → signature','Question copied four times'],1,'Mở bài → Lý do 1 kèm ví dụ → Lý do 2 kèm ví dụ → Kết luận.','B tạo mạch lập luận đầy đủ. Các phương án khác không phát triển hay bảo vệ quan điểm.','Essay 4 đoạn: mở bài – lý do 1 – lý do 2 – kết luận.'),
 sw(10,'Choose the best simple conclusion for an opinion response.',['Therefore, I believe flexible schedules benefit both employees and companies.','Flexible therefore company maybe.','I have no more words.','Because conclusion employee.'],0,'Vì vậy, tôi tin lịch làm việc linh hoạt có lợi cho cả nhân viên và công ty.','A nhắc lại quan điểm rõ ràng bằng câu hoàn chỉnh. B/D sai ngữ pháp; C không trả lời nhiệm vụ.','Kết luận: Therefore, I believe + opinion.'),
]

const enrich=question=>({...question,optionExplanations:question.options.map((option,index)=>index===question.correctAnswer?`Đúng: “${option}” phù hợp với cấu trúc và ngữ cảnh. ${question.explanation}`:`Loại ${String.fromCharCode(65+index)}: “${option}” không đáp ứng đúng loại thông tin/cấu trúc mà câu hỏi yêu cầu.`)})
const pool=(...ids)=>ids.flatMap(id=>fullQuestionBank[id]||[]).map(enrich)

export const linearStages=[
 {id:'reading-5',title:'Reading Part 5',subtitle:'Đuôi từ loại · 7 vị trí vàng · Liên từ/giới từ',pool:pool('part-5'),tips:[{rule:'Đuôi từ',detail:'Noun: -tion/-ment/-ness; Adj: -ive/-al/-able; Adv: -ly.',example:'The report was ___ prepared → carefully.'},{rule:'7 vị trí vàng',detail:'a/an/the + (Adj) + N; modal + V; be + Adj/V-ing/V3; have + V3.',example:'Employees must ___ ID cards → wear.'},{rule:'Liên từ hay giới từ?',detail:'Sau blank có S+V chọn because/although; sau là N/V-ing chọn because of/despite.',example:'because it rained / because of the rain.'}]},
 {id:'reading-6-7',title:'Reading Part 6 & Part 7',subtitle:'Điền đoạn · Scan/Skim săn keyword',pool:pool('part-6','part-7'),tips:[{rule:'Part 6',detail:'Thử giải bằng cấu trúc quanh blank trước; chỉ đọc rộng khi cần ngữ cảnh.',example:'has ___ → ưu tiên V3.'},{rule:'Part 7 làm ngược',detail:'Đọc câu hỏi → lấy keyword → scan passage → đọc vùng quanh keyword.',example:'reopen có thể được viết thành resume normal business hours.'},{rule:'Ưu tiên câu trực tiếp',detail:'WHO/WHEN/WHERE/HOW MUCH thường nhanh hơn NOT/implied.',example:'When → săn ngày, giờ hoặc từ chỉ thời gian.'}]},
 {id:'listening-1-2',title:'Listening Part 1 & Part 2',subtitle:'Being · Wh- · Same Sound · Trả lời gián tiếp',pool:pool('part-1','part-2'),tips:[{rule:'Part 1: đủ ba mảnh',detail:'Kiểm tra AI + ĐANG LÀM GÌ + Ở ĐÂU; không chọn chỉ vì nghe thấy danh từ trong tranh.',example:'Có car nhưng không có người sửa → repairing the car là sai.'},{rule:'Part 2: săn từ đầu',detail:'Where=nơi; When=thời gian; Who=người; Why=lý do; How often=tần suất.',example:'Where...? → In conference room B.'},{rule:'Bẫy âm và né tránh',detail:'Lặp âm thường là bẫy. Let me check/I don’t know có thể đúng khi hợp logic, không phải quy tắc 99%.',example:'Have you sent it? → I’ll do it this afternoon.'}]},
 {id:'listening-3-4',title:'Listening Part 3 & Part 4',subtitle:'Đọc trước câu hỏi · Paraphrase',pool:pool('part-3','part-4'),tips:[{rule:'Đọc trước',detail:'Rút câu hỏi thành 2–3 từ cần săn: WHERE + WOMAN + TOMORROW.',example:'What will the man do next? → MAN + NEXT.'},{rule:'Không dịch toàn audio',detail:'Nghe đúng thông tin câu hỏi cần; theo dõi but/however/actually để bắt ý bẻ hướng.',example:'We planned A, but actually C is available.'},{rule:'Paraphrase',detail:'Đáp án đúng thường khác chữ nhưng cùng nghĩa với audio.',example:'delay = leave later; purchase = buy; at no charge = free.'}]},
 {id:'speaking-writing',title:'Speaking & Writing 150+',subtitle:'Tả tranh · Email · Essay 4 đoạn',pool:speakingWritingQuestions.map(enrich),tips:[{rule:'Tả tranh 3 bước',detail:'Bối cảnh → người chính + is V-ing → hậu cảnh.',example:'This picture... In the center... In the background...'},{rule:'Email công sở',detail:'Cảm ơn → trả lời yêu cầu/giải pháp → mời liên hệ thêm.',example:'Thank you for... / I am pleased to... / Please feel free...'},{rule:'Essay 4 đoạn',detail:'Mở bài nêu ý → lý do 1 + ví dụ → lý do 2 + ví dụ → kết luận.',example:'I believe... First... For example... Therefore...'}]},
]

export const totalLinearQuestions=linearStages.length*10
