const META={
 writing:['V-ing','đang viết'],calling:['V-ing','đang gọi điện'],copying:['V-ing','đang sao chụp'],drinking:['V-ing','đang uống'],pouring:['V-ing','đang rót'],wiping:['V-ing','đang lau'],handing:['V-ing','đang đưa/trao'],wearing:['V-ing trạng thái','đang mặc/đội sẵn'],lifting:['V-ing','đang nâng'],using:['V-ing','đang sử dụng'],pushing:['V-ing','đang đẩy'],inspecting:['V-ing','đang kiểm tra'],paying:['V-ing','đang thanh toán'],pointing:['V-ing','đang chỉ'],shaking:['V-ing','đang bắt tay'],crossing:['V-ing','đang băng qua'],walking:['V-ing','đang đi bộ'],waiting:['V-ing','đang chờ'],parked:['V3/ed trạng thái','được đỗ'],stacked:['V3/ed trạng thái','được xếp chồng'],arranged:['V3/ed trạng thái','được sắp xếp'],docked:['V3/ed trạng thái','được neo đậu'],casting:['V-ing','đang tạo/đổ bóng'],being:['Trợ động từ bị động','đang được tác động'],putting:['V-ing hành động','đang mặc/đội vào'],
}
const vocabulary=options=>Object.entries(META).filter(([word])=>options.some(option=>option.toLowerCase().includes(word))).map(([word,[type,meaning]])=>({word,type,meaning}))
const make=(id,topicKey,actionKey,imageUrl,options,correctAnswer,vietnameseTranslation,explanation,fastTip)=>{
 const audioText=options.map((option,index)=>`${String.fromCharCode(65+index)}. ${option}`).join(' ')
 return{id:`part-1-${id}`,part:'part-1',topicKey,actionKey,imageUrl,question:'',passage:'',audioText,speech:audioText,transcript:audioText,transcriptTranslation:vietnameseTranslation,options,correctAnswer,vocabularyBreakdown:vocabulary(options),optionsMeaning:options.map(option=>({word:option,type:'Câu mô tả tranh',meaning:'Xem bản dịch và phân tích ngữ cảnh'})),vietnameseTranslation,explanation,fastTip,audioUrl:''}
}

export const part1QuestionPool=[
 make(1,'office-whiteboard','writing-board','https://images.unsplash.com/photo-1531482615713-2afd69097998?w=1000&auto=format&fit=crop&q=85',['A woman is writing on a board.','A board is being carried outside.','Some papers are being copied.','A woman is closing the curtains.'],0,'Một phụ nữ đang viết lên bảng.','Tay người phụ nữ hướng vào bảng và đang viết nên A đúng. B/C dùng being nhưng không có hành động tương ứng; D nói sai vật thể.','Nhìn bàn tay và bề mặt đang tác động: writing on a board.'),
 make(2,'office-phone','calling-phone','https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=1000&auto=format&fit=crop&q=85',['A woman is making a phone call.','A phone is being repaired.','She is putting on a headset.','She is filing some documents.'],0,'Một phụ nữ đang gọi điện thoại.','Điện thoại đang được giữ sát tai nên A đúng. B bịa hành động sửa chữa; C là đang đeo vào nhưng thiết bị đã ở vị trí sử dụng; D không có hành động xếp hồ sơ.','Vật ở sát tai + miệng đang nói → making a phone call.'),
 make(3,'office-copier','copying-documents','https://images.unsplash.com/photo-1560264280-88b68371db39?w=1000&auto=format&fit=crop&q=85',['A man is copying some documents.','Some documents are being shredded.','The machine is being delivered.','A man is pouring a beverage.'],0,'Một người đàn ông đang sao chụp tài liệu.','Người đứng cạnh máy và thao tác giấy nên A đúng. B/C là bẫy being không có người thực hiện; D sai đồ vật.','Máy văn phòng + giấy trên tay → copying documents.'),
 make(4,'office-coffee','drinking-coffee','https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=1000&auto=format&fit=crop&q=85',['A worker is drinking from a cup.','Coffee is being poured into several cups.','The laptop is being packed away.','The worker is wiping the desk.'],0,'Một nhân viên đang uống bằng cốc.','Cốc được đưa lên miệng nên A đúng. B cần dòng nước đang rót; C/D không khớp hành động.','Cốc sát miệng = drinking; nghiêng bình vào cốc = pouring.'),
 make(5,'restaurant-pouring','pouring-water','https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?w=1000&auto=format&fit=crop&q=85',['A server is pouring water into a glass.','The glasses are being stacked in a box.','A customer is wiping the floor.','A menu is being hung on a wall.'],0,'Một nhân viên phục vụ đang rót nước vào ly.','Có dòng nước từ bình xuống ly nên A đúng. Các đáp án B/D dùng being nhưng sai hành động; C sai đối tượng và vị trí.','Thấy bình nghiêng + ly → săn pouring into.'),
 make(6,'restaurant-cleaning','wiping-table','https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?w=1000&auto=format&fit=crop&q=85',['An employee is wiping a table.','A table is being moved outdoors.','Some dishes are being served to guests.','An employee is folding a menu.'],0,'Một nhân viên đang lau bàn.','Tay cầm khăn tiếp xúc mặt bàn nên A đúng. B/C/D thêm hoạt động không thấy trong ảnh.','Khăn + mặt bàn → wiping the table.'),
 make(7,'restaurant-menu','handing-menu','https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1000&auto=format&fit=crop&q=85',['A server is handing a menu to a customer.','A customer is paying at a register.','Menus are being printed.','The server is clearing every table.'],0,'Nhân viên phục vụ đang đưa thực đơn cho khách.','Vật được trao giữa hai người là menu nên A đúng. B không có quầy thanh toán; C là bẫy being; D nói quá mức every table.','Hai người + vật chuyển từ tay này sang tay kia → handing.'),
 make(8,'construction-hat','wearing-hard-hat','https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=1000&auto=format&fit=crop&q=85',['A worker is wearing a hard hat.','A worker is putting on a hard hat.','The helmet is being painted.','The worker is opening a suitcase.'],0,'Một công nhân đang đội mũ bảo hộ.','Mũ đã nằm trên đầu nên dùng wearing. Putting on chỉ đúng khi tay đang đưa mũ lên đầu; C/D không có trong ảnh.','Đã ở trên người = wearing; đang mặc/đội vào = putting on.'),
 make(9,'construction-box','lifting-box','https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=1000&auto=format&fit=crop&q=85',['A worker is lifting a box.','Several boxes are being opened by customers.','A worker is drawing a map.','The equipment is being washed.'],0,'Một công nhân đang nâng một chiếc hộp.','Hai tay giữ hộp và tư thế nâng lên khớp A. B thêm customers; C/D sai hành động.','Tay dưới vật + người dùng lực → lifting/carrying.'),
 make(10,'construction-tools','using-equipment','https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=1000&auto=format&fit=crop&q=85',['A worker is using some equipment.','The tools are being displayed for sale.','A wall is being covered with fabric.','The worker is shaking hands.'],0,'Một công nhân đang sử dụng thiết bị.','Người công nhân đang thao tác trực tiếp công cụ nên A đúng. B/C là trạng thái bị động sai ngữ cảnh; D cần hai người.','Nhìn điểm tiếp xúc giữa tay và dụng cụ → using equipment.'),
 make(11,'shopping-cart','pushing-cart','https://images.unsplash.com/photo-1534723452862-4c874018d66d?w=1000&auto=format&fit=crop&q=85',['A shopper is pushing a cart.','A cart is being repaired near the entrance.','Products are being removed from every shelf.','A shopper is carrying a bicycle.'],0,'Một người mua hàng đang đẩy xe hàng.','Hai tay đặt trên tay cầm xe đẩy và người di chuyển nên A đúng. B/C dùng being nhưng không có tác động; D sai vật.','Hai tay trên tay cầm + bánh xe → pushing a cart.'),
 make(12,'shopping-shelf','inspecting-shelf','https://images.unsplash.com/photo-1542838132-92c53300491e?w=1000&auto=format&fit=crop&q=85',['A customer is inspecting an item on a shelf.','The shelves are being installed.','A customer is wiping a shopping cart.','All the items are being packed.'],0,'Một khách hàng đang kiểm tra món hàng trên kệ.','Khách đang nhìn/cầm sản phẩm gần kệ nên A đúng. B/D bịa hoạt động lắp đặt/đóng gói; C sai hành động.','Mắt nhìn gần + sản phẩm trên tay → inspecting an item.'),
 make(13,'shopping-checkout','paying-register','https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1000&auto=format&fit=crop&q=85',['A customer is paying at a counter.','The counter is being moved.','A cashier is stacking chairs.','Some money is being displayed in a window.'],0,'Một khách hàng đang thanh toán tại quầy.','Giao dịch diễn ra tại quầy nên A đúng. B/C/D đưa vật đúng bối cảnh nhưng hành động sai.','Quầy + thẻ/tiền đưa ra → paying at a counter.'),
 make(14,'meeting-presentation','pointing-screen','https://images.unsplash.com/photo-1556761175-b413da4baf72?w=1000&auto=format&fit=crop&q=85',['A presenter is pointing at a screen.','The screen is being taken down.','Everyone is writing on the wall.','The presenter is closing a window.'],0,'Người thuyết trình đang chỉ vào màn hình.','Cánh tay hướng về màn hình nên A đúng. B là being trap; C dùng everyone quá mức; D sai vật.','Tay duỗi + màn hình → pointing at a screen.'),
 make(15,'meeting-documents','handing-documents','https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=1000&auto=format&fit=crop&q=85',['One colleague is handing documents to another.','The documents are being thrown away.','Everyone is leaving the building.','A table is being folded.'],0,'Một đồng nghiệp đang đưa tài liệu cho người khác.','Tài liệu nằm giữa hai người và đang được trao nên A đúng. B/D là being trap; C sai hành động chung.','Vật nằm giữa hai bàn tay → handing documents.'),
 make(16,'business-handshake','shaking-hands','https://images.unsplash.com/photo-1521791136064-7986c2920216?w=1000&auto=format&fit=crop&q=85',['Two businesspeople are shaking hands.','They are pointing at a monitor.','Some jackets are being put on.','They are exchanging boxes.'],0,'Hai doanh nhân đang bắt tay nhau.','Hai bàn tay nắm nhau nên A đúng. B/D sai vật; C dùng bị động và không có hành động mặc áo.','Hai người đối diện + tay nắm nhau → shaking hands.'),
 make(17,'street-crossing','crossing-street','https://images.unsplash.com/photo-1539008835657-9e8e9680c956?w=1000&auto=format&fit=crop&q=85',['Some pedestrians are crossing the street.','The street is being repaired.','People are waiting inside a restaurant.','Cars are being washed.'],0,'Một số người đi bộ đang băng qua đường.','Người đang di chuyển trên phần đường qua lại nên A đúng. B/D là being trap; C sai vị trí.','Người trên vạch/đường + đang bước → crossing the street.'),
 make(18,'riverside-walk','walking-river','https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1000&auto=format&fit=crop&q=85',['People are walking along a riverside path.','A path is being widened by workers.','Boats are being carried across the road.','People are entering an office.'],0,'Mọi người đang đi bộ dọc lối đi ven sông.','Người đi trên lối cạnh mặt nước nên A đúng. B/C dùng being nhưng không có người tác động; D sai địa điểm.','Săn giới từ vị trí: along a path, beside a river.'),
 make(19,'bus-stop','waiting-bus','https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=1000&auto=format&fit=crop&q=85',['Several people are waiting for a bus.','A bus stop is being painted.','Passengers are crossing a river.','People are loading boxes into a store.'],0,'Một số người đang chờ xe buýt.','Nhóm người đứng tại điểm dừng phù hợp A. B là being trap; C/D sai môi trường và hành động.','Đứng yên theo nhóm tại biển/trạm → waiting for a bus.'),
 make(20,'parking-row','parked-row','https://images.unsplash.com/photo-1506521781263-d8422e82f27a?w=1000&auto=format&fit=crop&q=85',['Cars are parked in a row.','Drivers are repairing every car.','The parking area is being swept.','Cars are crossing an intersection.'],0,'Các ô tô được đỗ thành một hàng.','Ảnh tĩnh không người nên trạng thái are parked đúng. B/C thêm người/hành động không thấy; D sai trạng thái.','Tranh không người: ưu tiên trạng thái parked/arranged/docked.'),
 make(21,'library-shelves','stacked-shelves','https://images.unsplash.com/photo-1521587760476-6c12a4b040da?w=1000&auto=format&fit=crop&q=85',['Books are stacked on shelves.','A librarian is handing out menus.','The shelves are being carried away.','People are wiping the windows.'],0,'Sách được xếp trên các kệ.','Trạng thái sách nằm ngay ngắn trên kệ khớp A. B/C/D thêm người hoặc hành động không tồn tại.','Không người + vật có trật tự → stacked/arranged/displayed.'),
 make(22,'empty-conference','arranged-chairs','https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=1000&auto=format&fit=crop&q=85',['Chairs are arranged around a table.','A meeting is being conducted.','People are putting on jackets.','The table is being delivered.'],0,'Ghế được sắp xếp quanh bàn.','Phòng trống nên chỉ mô tả trạng thái ghế. B/C/D bịa người hoặc hành động đang diễn ra.','Phòng trống: are arranged đúng; is being conducted thường sai.'),
 make(23,'harbor-boats','docked-boats','https://images.unsplash.com/photo-1500375592092-40eb2168fd21?w=1000&auto=format&fit=crop&q=85',['Several boats are docked at a harbor.','Workers are lifting the boats onto a truck.','The water is being poured into containers.','Passengers are wiping a platform.'],0,'Một số thuyền đang neo tại bến cảng.','Các thuyền đứng yên sát bến nên are docked đúng. B/C/D suy diễn hoạt động không có.','Thuyền đứng yên sát cầu tàu → docked/moored.'),
 make(24,'park-shadows','casting-shadows','https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1000&auto=format&fit=crop&q=85',['Trees are casting shadows on a path.','The trees are being cut down.','A path is being painted indoors.','People are stacking branches.'],0,'Cây đang đổ bóng xuống lối đi.','Ánh sáng tạo bóng cây trên đường nên A đúng. B/C/D là các hành động không thấy.','Tranh phong cảnh: chú ý ánh sáng, bóng và quan hệ vị trí.'),
]
