import {useMemo,useState} from 'react'
import {ArrowLeft,ArrowRight,BookOpen,Check,CheckCircle2,Headphones,Leaf,Lightbulb,MessageSquareText,Play,RotateCcw,Sparkles,Volume2,XCircle} from 'lucide-react'

const stages=[
 {id:'vocabulary',number:1,title:'50 từ công sở “gặp là có điểm”',subtitle:'Flashcard nhanh · Nhớ nghĩa qua ngữ cảnh',icon:BookOpen,color:'mint',formulas:[['Nhìn từ trong cụm','Không học một từ đứng riêng. Học appointment trong make an appointment.'],['Ôn ngắt quãng','Sai thì ôn lại sau 1 ngày; đúng thì ôn sau 3–7 ngày.'],['Đọc thành tiếng','Nghe rồi nhắc lại để nhớ cả âm và nghĩa.']],examples:[['appointment','Cuộc hẹn','I made an appointment with the manager.'],['deadline','Hạn chót','Please submit the form before the deadline.'],['available','Có sẵn/rảnh','The meeting room is available at two.']],practice:[['“shipment” nghĩa là gì?',['cuộc họp','lô hàng','hóa đơn'],1],['Chọn nghĩa của “deadline”.',['hạn chót','giảm giá','nhân viên'],0],['“available” gần nghĩa nhất với...',['bị hỏng','có sẵn','đắt tiền'],1],['We need to _____ the meeting.',['confirm','confirmation','confirming'],0],['“invoice” là...',['hóa đơn','nhà kho','ứng viên'],0],['A qualified _____ repaired the printer.',['technician','technical','technically'],0],['“refund” nghĩa là...',['đặt chỗ','hoàn tiền','bảo trì'],1],['The package arrived at the _____.',['warehouse','deadline','conference'],0],['Please _____ the application today.',['submit','supplier','submission'],0],['“reliable” nghĩa là...',['đáng tin cậy','miễn phí','thuận tiện'],0]]},
 {id:'part5',number:2,title:'Mẹo giải Part 5 trong 5 giây',subtitle:'Nhìn đuôi từ · Liên từ/Giới từ',icon:Sparkles,color:'purple',formulas:[['a/an/the + Adj + Noun','Sau mạo từ, tìm danh từ; nếu còn một ô trước danh từ thì thường cần tính từ.'],['Verb + Adverb','Từ mô tả cách thực hiện hành động thường là trạng từ có -ly.'],['Although + S + V / Despite + N','Nhìn ngay phía sau để phân biệt liên từ với giới từ.']],examples:[['The manager gave a _____ presentation.','Trước presentation là danh từ → cần tính từ.','successful'],['Staff worked _____.','Bổ nghĩa cho worked → cần trạng từ.','efficiently'],['_____ the rain, the event continued.','Sau ô trống là cụm danh từ the rain → Despite.','Despite']],practice:[['The report was _____ prepared.',['careful','carefully','care'],1],['We need final _____.',['approve','approval','approved'],1],['_____ it rained, the event continued.',['Although','Despite','During'],0],['_____ the rain, we continued.',['Although','Despite','Because'],1],['The system is very _____.',['efficiency','efficient','efficiently'],1],['Please _____ the form.',['completion','complete','completely'],1],['She responded _____.',['quick','quickly','quickness'],1],['The _____ will call you.',['manage','manager','managerial'],1],['We canceled because _____ the storm.',['of','that','during'],0],['The product is _____ available.',['current','currently','currency'],1]]},
 {id:'listening',number:3,title:'Phản xạ nghe Part 1 & Part 2',subtitle:'Loại “being” · Né bẫy Yes/No',icon:Headphones,color:'orange',formulas:[['Part 1: nhìn tay và mắt','Chọn hành động thấy rõ; không đoán cảm xúc hoặc mục đích.'],['Being + V3 cần hành động','Tranh tĩnh thường dùng is/are + V3, không dùng being nếu không thấy ai đang làm.'],['Wh- loại Yes/No','Where cần nơi, When cần thời gian, Who cần người.']],examples:[['Where is the meeting room?','Where hỏi nơi → gạch “Yes, it is”.','On the second floor.'],['The chairs are arranged in rows.','Không có người đang xếp → trạng thái are arranged.','Trạng thái tĩnh'],["Why don’t we leave early?",'Đây là đề nghị, không phải hỏi lý do.','That sounds good.']],practice:[['Where should I put this box?',['Yes, it is.','Near the door.','Tomorrow.'],1],['When will the store open?',['At nine.','On Main Street.','The manager.'],0],['Who ordered the supplies?',['Yesterday.','Ms. Lee did.','In the office.'],1],['Why was it delayed?',['Because of the rain.','At noon.','Yes, it was.'],0],["Would you like some coffee?",['That would be nice.','In the kitchen.','At ten.'],0],['Tranh tĩnh: ghế đã xếp thành hàng.',['The chairs are being arranged.','The chairs are arranged in rows.','A man arranges chairs.'],1],['How often do you inspect it?',['Every month.','For an hour.','At the factory.'],0],['Could you send the file?',['Certainly.','The blue file.','By email?'],0],['Which train should we take?',['The express train.','At platform two.','Yes, we should.'],0],['Did John call the client?',["He left her a message.",'The phone is new.','At his desk.'],0]]},
 {id:'templates',number:4,title:'Mẫu câu Speaking & Writing bỏ túi',subtitle:'Tả tranh 3 bước · Email mục tiêu 150+',icon:MessageSquareText,color:'blue',formulas:[['Tả tranh 3 bước','Nơi chốn → người/hành động → foreground/background.'],['Email 3 phần','Thank you → trả lời đủ yêu cầu → Please let me know if...'],['Ưu tiên câu chắc chắn','Câu ngắn, đúng ngữ pháp tốt hơn câu dài nhưng nhiều lỗi.']],examples:[['Mở bài tả tranh','Nêu nơi chốn an toàn.','This picture was taken in an office.'],['Nói hành động','Dùng is/are + V-ing.','A woman is reviewing a document.'],['Kết email','Mời người nhận liên hệ lại.','Please let me know if you need further information.']],practice:[['Câu tả tranh đúng là...',['A woman working.','A woman is working at a desk.','Woman work desk.'],1],['Mở email lịch sự là...',['Hey!','Thank you for your email.','What do you need?'],1],['In the _____, a man is standing.',['background','yesterday','perhaps'],0],['Chọn câu đúng.',['Two people is talking.','Two people are talking.','Two people talking.'],1],['Cách kết thư phù hợp?',['Best regards,','See ya!','Answer now.'],0],['Câu nào không suy diễn?',['He is definitely a manager.','A man is holding a document.','He will sign it tomorrow.'],1],['Khung nêu nơi chốn?',['This picture was taken at...','I knowing this place...','Yesterday place...'],0],['Trả lời yêu cầu giờ mở cửa?',['We are open from 9 to 6.','Yes, opening.','Maybe time.'],0],['Cụm chuyển sang chi tiết sau?',['In the background,...','I am background...','Background yesterday...'],0],['Câu mời liên hệ lại?',['Please let me know if you need help.','Tell me fast.','This is finish.'],0]]},
]

const speak=text=>{if(!('speechSynthesis'in window))return;const utterance=new SpeechSynthesisUtterance(text);utterance.lang='en-US';speechSynthesis.cancel();speechSynthesis.speak(utterance)}

export default function ZeroToHeroPage({initialStage=null,onBack,onOpenFlash}){
 const[activeId,setActiveId]=useState(initialStage)
 const[answers,setAnswers]=useState({})
 const[completed,setCompleted]=useState(()=>{try{return JSON.parse(localStorage.getItem('toeic-zero-hero-progress'))||[]}catch{return[]}})
 const active=useMemo(()=>stages.find(stage=>stage.id===activeId),[activeId])
 const choose=(questionIndex,optionIndex)=>setAnswers(old=>({...old,[questionIndex]:optionIndex}))
 const finish=()=>{const next=[...new Set([...completed,active.id])];setCompleted(next);localStorage.setItem('toeic-zero-hero-progress',JSON.stringify(next))}
 const openStage=id=>{setActiveId(id);setAnswers({});window.scrollTo({top:0,behavior:'smooth'})}
 if(!active)return <div className="zero-page"><header className="zero-head"><button onClick={onBack}><ArrowLeft/> Dashboard</button><span className="kicker">ZERO-TO-HERO MODE</span><h1>🌱 Lộ Trình Cứu Nguy Cho Người Mất Gốc</h1><p>Mục tiêu 450 Listening & Reading · 150 Speaking & Writing</p><div className="zero-progress"><div><i style={{width:`${completed.length/4*100}%`}}/></div><strong>Đã hoàn thành {completed.length}/4 chặng</strong></div></header><div className="stage-list">{stages.map(stage=>{const Icon=stage.icon,done=completed.includes(stage.id);return <button className={`stage-card ${stage.color}`} onClick={()=>openStage(stage.id)} key={stage.id}><b>CHẶNG {stage.number}</b><span><Icon/></span><div><h2>{stage.title}</h2><p>{stage.subtitle}</p></div>{done?<CheckCircle2 className="stage-done"/>:<ArrowRight/>}</button>})}</div>{completed.length===4&&<div className="hero-complete"><CheckCircle2/><h2>Bạn đã hoàn thành khóa nhập môn!</h2><p>Hãy chuyển sang mini-test từng Part để tiếp tục tăng điểm.</p></div>}</div>
 const correctCount=active.practice.filter((q,i)=>answers[i]===q[2]).length
 const allAnswered=Object.keys(answers).length===10
 return <div className="zero-page lesson"><header className="stage-head"><button onClick={()=>setActiveId(null)}><ArrowLeft/> 4 chặng</button><span>CHẶNG {active.number}/4</span><h1>{active.title}</h1><p>{active.subtitle}</p></header><section className="zero-section"><div className="zero-label"><Lightbulb/> PHẦN 1 · CÔNG THỨC SIÊU NGẮN</div><div className="zero-formulas">{active.formulas.map(([title,text],i)=><article key={title}><b>{i+1}</b><div><h3>{title}</h3><p>{text}</p></div></article>)}</div>{active.id==='vocabulary'&&<button className="open-flash" onClick={onOpenFlash}><BookOpen/> Mở bộ Flashcard 50 từ</button>}</section><section className="zero-section"><div className="zero-label"><Sparkles/> PHẦN 2 · 3 VÍ DỤ CẦM TAY CHỈ VIỆC</div><div className="walkthrough">{active.examples.map(([prompt,analysis,result],i)=><article key={prompt}><span>VÍ DỤ {i+1}</span><h3>{prompt}</h3><p><strong>Nhận diện → Loại trừ:</strong> {analysis}</p><div><Check/> Chốt đáp án: <b>{result}</b>{active.id==='listening'&&<button onClick={()=>speak(prompt)}><Volume2/></button>}</div></article>)}</div></section><section className="zero-section practice"><div className="zero-label"><Play/> PHẦN 3 · 10 CÂU THỰC HÀNH</div>{active.practice.map((question,qIndex)=><article key={question[0]}><h3><span>{qIndex+1}</span>{question[0]}{active.id==='listening'&&<button onClick={()=>speak(question[0])}><Volume2/></button>}</h3><div>{question[1].map((option,oIndex)=>{const selected=answers[qIndex]===oIndex,answered=answers[qIndex]!==undefined,correct=oIndex===question[2];return <button disabled={answered} className={answered&&correct?'correct':selected?'wrong':''} onClick={()=>choose(qIndex,oIndex)} key={option}><b>{String.fromCharCode(65+oIndex)}</b>{option}{answered&&correct&&<Check/>}{selected&&!correct&&<XCircle/>}</button>})}</div></article>)}<div className="stage-result"><span>Điểm hiện tại: <strong>{correctCount}/10</strong></span>{allAnswered?<button onClick={finish}><CheckCircle2/> Hoàn thành chặng</button>:<small>Trả lời đủ 10 câu để hoàn thành</small>}</div></section>{completed.includes(active.id)&&<div className="stage-finished"><CheckCircle2/> Chặng này đã hoàn thành <button onClick={()=>setAnswers({})}><RotateCcw/> Luyện lại</button></div>}</div>
}
